// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope, ParseCrud) {
    var ItemsRepo, error, success;
    ItemsRepo = new ParseCrud('ItemsRepo');
    scope.error = scope.success = '';
    scope.model = {};
    success = function(res) {
      console.log(res);
      return scope.$apply(function() {
        return scope.$parent.entities = res;
      });
    };
    error = function(e) {
      console.log(e);
      return scope.$apply(function() {
        return scope.error = 'Error occured';
      });
    };
    return ItemsRepo.list(success, error);
  };

  angular.module('manageApp').controller('FitnessItemListCtrl', ['$scope', 'ParseCrud', controller]);

}).call(this);

/*
//@ sourceMappingURL=list.map
*/
