// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope, ParseCrud) {
    var Items, error, success;
    Items = new ParseCrud('Items');
    scope.error = scope.success = '';
    success = function(res) {
      console.log(res);
      return scope.$apply(function() {
        return scope.entities = res;
      });
    };
    error = function(e) {
      console.log(e);
      return scope.$apply(function() {
        return scope.error = 'Error occured';
      });
    };
    return Items.list(success, error);
  };

  angular.module('manageApp').controller('FitnessItemMineCtrl', ['$scope', 'ParseCrud', controller]);

}).call(this);

/*
//@ sourceMappingURL=mine.map
*/
