// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    var Contact;
    Contact = Parse.Object.extend('Contact');
    scope.contacts = [];
    scope.model = {
      name: '',
      email: ''
    };
    scope.load = function() {
      var query;
      query = new Parse.Query('Contact');
      return query.find({
        success: function(res) {
          return scope.$apply(function() {
            return scope.contacts = res;
          });
        }
      });
    };
    scope.load();
    return scope.add = function(form) {
      var contact;
      contact = new Contact();
      contact.set('name', scope.model.name);
      contact.set('email', scope.model.email);
      contact.setACL(new Parse.ACL(Parse.User.current()));
      return contact.save(null, {
        success: function() {
          scope.load();
          return scope.$apply(function() {
            scope.model.name = '';
            return scope.model.email = '';
          });
        }
      });
    };
  };

  angular.module('manageApp').controller('ContactsCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=contacts.map
*/
