// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {};

  angular.module('manageApp').controller('PomodoroCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=pomodoro.map
*/
