// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function($scope) {};

  angular.module('manageApp').controller('SigninCtrl', ['$scope', controller]);

}).call(this);
