// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    if (scope.user) {
      scope.go('/');
    }
    scope.onSuccess = function() {
      return scope.go('/');
    };
    return scope.onError = function(user, error) {
      scope.error = "Please, check your username and password.";
      return console.log(scope.error);
    };
  };

  angular.module('manageApp').controller('SignupCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=signup.map
*/
