// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: crud', function() {
    var crud;
    beforeEach(module('drinksApp'));
    crud = {};
    beforeEach(inject(function(_crud_) {
      return crud = _crud_;
    }));
    return it('should do something', function() {
      return expect(!!crud).toBe(true);
    });
  });

}).call(this);
