// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: drink', function() {
    var drink;
    beforeEach(module('drinksApp'));
    drink = {};
    beforeEach(inject(function(_drink_) {
      return drink = _drink_;
    }));
    return it('should do something', function() {
      return expect(!!drink).toBe(true);
    });
  });

}).call(this);
