// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: point', function() {
    var point;
    beforeEach(module('drinksApp'));
    point = {};
    beforeEach(inject(function(_point_) {
      return point = _point_;
    }));
    return it('should do something', function() {
      return expect(!!point).toBe(true);
    });
  });

}).call(this);
