// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Service: settings', function() {
    var settings;
    beforeEach(module('drinksApp'));
    settings = {};
    beforeEach(inject(function(_settings_) {
      return settings = _settings_;
    }));
    return it('should do something', function() {
      return expect(!!settings).toBe(true);
    });
  });

}).call(this);
