// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: manage', function() {
    var element;
    beforeEach(module('manageApp'));
    element = {};
    return it('should make hidden element visible', inject(function($rootScope, $compile) {
      element = angular.element('<manage></manage>');
      element = $compile(element)($rootScope);
      return expect(element.text()).toBe('this is the manage directive');
    }));
  });

}).call(this);
