// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: pomodorolist', function() {
    var scope;
    beforeEach(module('drinksApp'));
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      return scope = $rootScope.$new();
    }));
    return it('should make hidden element visible', inject(function($compile) {
      var element;
      element = angular.element('<pomodorolist></pomodorolist>');
      element = $compile(element)(scope);
      return expect(element.text()).toBe('this is the pomodorolist directive');
    }));
  });

}).call(this);
