// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {};

  angular.module('drinksApp').controller('DrinkEditCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=edit.map
*/
