// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope, Service) {
    return scope.drinks = [
      {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }, {
        name: 'Espresso',
        description: 'Coffee Drink',
        img: "http://placehold.it/50x50"
      }
    ];
  };

  angular.module('drinksApp').controller('DrinkListCtrl', ['$scope', 'DrinkService', controller]);

}).call(this);

/*
//@ sourceMappingURL=list.map
*/
