// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    return Service.create(Service.newCoffee());
  };

  angular.module('drinksApp').controller('DrinkViewCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=view.map
*/
