// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope) {};

  angular.module('manageApp').controller('FitnessConsumptionCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=consumption.map
*/
