// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('manageApp').controller('FitnessResportsCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);

/*
//@ sourceMappingURL=resports.map
*/
