// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: SigninCtrl', function() {
    var SigninCtrl, scope;
    beforeEach(module('drinksApp'));
    SigninCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return SigninCtrl = $controller('SigninCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);
