// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope, Service) {
    var addCB;
    scope.entities = [];
    Service.list(function(results) {
      return scope.$apply(function() {
        return scope.entities = results;
      });
    });
    scope.remove = function(model) {
      return Service.remove(model, function() {
        return scope.$apply(function() {
          return scope.entities = _.filter(scope.entities, function(d) {
            return d.id !== model.id;
          });
        });
      });
    };
    addCB = function(result) {
      return scope.$apply(function() {
        return scope.entities.push(result);
      });
    };
    return scope.add = function() {
      return Service.add(addCB, scope.name);
    };
  };

  angular.module('drinksApp').controller('IdeaListCtrl', ['$scope', 'Idea', controller]);

}).call(this);

/*
//@ sourceMappingURL=list.map
*/
