// Generated by CoffeeScript 1.6.3
(function() {
  var filter;

  filter = function() {
    return function(input) {
      return "" + input;
    };
  };

  angular.module('manageApp').filter('timer', filter);

}).call(this);
