// Generated by CoffeeScript 1.6.3
(function() {
  var filter;

  filter = function() {
    return function(input) {
      input = parseInt(input, 10);
      if (input > 59) {
        input = parseInt(input / 60, 10);
      }
      return "" + input;
    };
  };

  angular.module('drinksApp').filter('timer', filter);

}).call(this);

/*
//@ sourceMappingURL=timer.map
*/
