// Generated by CoffeeScript 1.6.3
(function() {
  var filter;

  filter = function() {
    return function(input) {
      if (input) {
        return 'Yes';
      } else {
        return 'No';
      }
    };
  };

  angular.module('drinksApp').filter('truthy', filter);

}).call(this);

/*
//@ sourceMappingURL=truthy.map
*/
