// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope, params) {
    var Drink, query;
    scope.model = {};
    Drink = Parse.Object.extend("Product");
    query = new Parse.Query(Drink);
    query.get(params.id, {
      success: function(result) {
        scope.obj = result;
        return scope.$apply(function() {
          return scope.model = result._serverData;
        });
      },
      error: function(e) {
        return console.log(e);
      }
    });
    return scope.update = function(form) {
      _.each(scope.model, function(v, k) {
        return scope.obj.set(k, v);
      });
      return scope.obj.save({
        success: function(r) {
          return scope.go("/drink/view/" + params.id);
        },
        error: function(e) {
          return console.log(e);
        }
      });
    };
  };

  angular.module('drinksApp').controller('DrinkEditCtrl', ['$scope', '$routeParams', controller]);

}).call(this);

/*
//@ sourceMappingURL=edit.map
*/
