// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    return scope.tab = 'pomodoro';
  };

  angular.module('manageApp').controller('TimeListCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=list.map
*/
