// Generated by CoffeeScript 1.6.3
(function() {
  var service;

  service = function() {
    var crud, newCoffee, newWater;
    newWater = function(name, cal) {
      if (name == null) {
        name = 'Water';
      }
      if (cal == null) {
        cal = 0;
      }
      return {
        name: "" + name,
        cal: cal
      };
    };
    newCoffee = function(name, cal) {
      if (name == null) {
        name = 'Coffee';
      }
      if (cal == null) {
        cal = 0;
      }
      return {
        name: "" + name,
        cal: cal
      };
    };
    crud = crud().config("drink");
    crud.newCoffee = newCoffee;
    return crud;
  };

  angular.module('drinksApp').factory('Drink', ['Crud', service]);

}).call(this);

/*
//@ sourceMappingURL=drink.map
*/
