// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var Service;

  Service = function() {
    var Crud;
    return Crud = (function() {
      function Crud(name, _private) {
        this.name = name;
        this["private"] = _private != null ? _private : true;
        this["class"] = Parse.Object.extend(this.name);
      }

      Crud.prototype.save = function(obj, cb, errCB) {
        var instance, k, v;
        instance = new this["class"]();
        for (k in obj) {
          v = obj[k];
          instance.set(k, v);
        }
        if (this["private"]) {
          instance.setACL(new Parse.ACL(Parse.User.current()));
        }
        return instance.save(null, {
          success: cb,
          error: errCB
        });
      };

      Crud.prototype.get = function(id, cb, errCB) {
        var query;
        query = new Parse.Query(this["class"]);
        return query.get(id, {
          success: cb,
          error: errCB
        });
      };

      Crud.prototype.update = function(model, cb, errCB) {
        return model.save({
          success: cb,
          error: errCB
        });
      };

      Crud.prototype.remove = function(model, cb, errCB) {
        return model.destroy({
          success: cb,
          error: errCB
        });
      };

      Crud.prototype.list = function(cb, errCB) {
        var query;
        query = new Parse.Query(this["class"]);
        query.descending('createdAt');
        return query.find({
          success: cb,
          error: errCB
        });
      };

      return Crud;

    })();
  };

  angular.module('manageApp').service('ParseCrud', [Service]);

}).call(this);

/*
//@ sourceMappingURL=parsecrud.map
*/
