// Generated by CoffeeScript 1.6.3
(function() {
  var service;

  service = function() {
    return crud().config("point");
  };

  angular.module('drinksApp').factory('Point', ['Crud', service]);

}).call(this);

/*
//@ sourceMappingURL=point.map
*/
