// Generated by CoffeeScript 1.6.3
(function() {
  var service;

  service = function(Crud) {
    return Crud().config("settings");
  };

  angular.module('drinksApp').factory('Settings', ['Crud', service]);

}).call(this);

/*
//@ sourceMappingURL=settings.map
*/
