// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    var Drink, query;
    scope.manage = [];
    Drink = Parse.Object.extend("Product");
    query = new Parse.Query(Drink);
    query.equalTo("type", "drink");
    query.find({
      success: function(results) {
        return scope.$apply(function() {
          return scope.manage = _.map(results, function(d) {
            var x;
            x = d._serverData;
            x.id = d.id;
            return x;
          });
        });
      },
      error: function(error) {
        return console.log(error);
      }
    });
    return scope.remove = function(id) {
      Drink = Parse.Object.extend("Product");
      query = new Parse.Query(Drink);
      return query.get(id, {
        success: function(result) {
          return scope.$apply(function() {
            result.destroy();
            return scope.manage = _.filter(scope.manage, function(d) {
              return d.id !== id;
            });
          });
        },
        error: function(e) {
          return console.log(e);
        }
      });
    };
  };

  angular.module('manageApp').controller('DrinkListCtrl', ['$scope', controller]);

}).call(this);
