// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope, params) {
    scope.model = {
      subject: '',
      content: '',
      email: params.email
    };
    return scope.send = function() {
      return Parse.Cloud.run('mail', scope.model, {
        success: function(result) {
          return alert(result);
        },
        error: function(error) {}
      });
    };
  };

  angular.module('manageApp').controller('ContactsMailCtrl', ['$scope', '$routeParams', controller]);

}).call(this);

/*
//@ sourceMappingURL=mail.map
*/
