// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module("drinksApp").directive("activenavitem", function($location) {
    var postLink;
    return {
      restrict: "A",
      link: postLink = function(scope, element, attrs, controller) {
        return scope.$watch((function() {
          return $location.path();
        }), function(newValue, oldValue) {
          return $("li[matches]", element).each(function(k, li) {
            var $collapse, $li, pattern, regexp;
            $li = angular.element(li);
            pattern = $li.attr("matches");
            console.log(pattern);
            regexp = new RegExp("^" + pattern + "$", ["i"]);
            if (regexp.test(newValue)) {
              $li.addClass("active");
              $collapse = $li.find(".collapse.in");
              if ($collapse.length) {
                return $collapse.collapse("hide");
              }
            } else {
              return $li.removeClass("active");
            }
          });
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=activenavitem.map
*/
