// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    scope.statuses = ['created', 'done', 'working', 'paused'];
    scope.update = function(status) {
      scope.model.set('status', status);
      return scope.onChange()(scope.model);
    };
    return scope.doRemove = function() {
      return scope.remove()(scope.model);
    };
  };

  angular.module('manageApp').directive('doable', function() {
    return {
      templateUrl: 'views/directives/doable.html',
      restrict: 'E',
      scope: {
        model: '=',
        onChange: '&change',
        remove: '&remove'
      },
      replace: true,
      controller: ['$scope', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=doable.map
*/
