// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope, timeout) {
    var everySecond, pausesTime, timer;
    timer = null;
    pausesTime = _.reduce(_.map(scope.model.get('pauses'), function(p) {
      if (p.end) {
        return p.end - p.start;
      } else {
        return 0;
      }
    }), function(x, y) {
      return x + y;
    });
    if (pausesTime == null) {
      pausesTime = 0;
    }
    scope.count = (new Date() - scope.model.createdAt - pausesTime) / 1000;
    scope.count = scope.model.get('sprint') + scope.model.get('rest') - scope.count;
    everySecond = function() {
      var pause;
      timer = timeout(everySecond, 1000);
      pause = scope.model.get('pause');
      if (!(pause.start || scope.model.get('status') === 'done')) {
        if (scope.count > 0) {
          scope.count -= 1;
          if (scope.model.get('status') === 'work' && scope.count <= scope.model.get('rest')) {
            scope.model.set('status', 'rest');
            return scope.onChange()(scope.model);
          }
        } else {
          scope.model.set('status', 'done');
          return scope.onChange()(scope.model);
        }
      }
    };
    timeout(everySecond, 1000);
    scope.doPause = function() {
      var pause;
      pause = scope.model.get('pause');
      if (!pause.start) {
        scope.model.set('pause', {
          start: new Date(),
          end: null
        });
      } else {
        pause.end = new Date();
        scope.model.add('pauses', pause);
        scope.model.set('pause', {});
      }
      return scope.onChange()(scope.model);
    };
    scope.doRemove = function() {
      timeout.cancel(timer);
      return scope.remove()(scope.model);
    };
    return scope.$on('$routeChangeStart', function(next, current) {
      timeout.cancel(timer);
      return scope.onChange()(scope.model);
    });
  };

  angular.module('drinksApp').directive('durable', function() {
    return {
      templateUrl: 'views/directives/durable.html',
      restrict: 'E',
      scope: {
        model: '=',
        onChange: '&change',
        remove: '&remove'
      },
      replace: true,
      controller: ['$scope', '$timeout', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=durable.map
*/
