// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(location, scope, element, attrs) {
    var parts;
    parts = location.$$path.split('/');
    scope.page = parts[1];
    scope.action = parts[2];
    return scope.id = parts[3];
  };

  angular.module('manageApp').directive('entitynav', function() {
    return {
      templateUrl: 'views/directives/entitynav.html',
      restrict: 'E',
      scope: true,
      controller: ['$location', '$scope', '$element', '$attrs', controller]
    };
  });

}).call(this);
