// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope, timeout) {
    return scope.consumptionFilter = '';
  };

  angular.module('manageApp').directive('fitness', function() {
    return {
      templateUrl: "views/directives/fitness.html",
      restrict: 'E',
      transclude: true,
      replace: true,
      scope: {
        selectedtab: '@selectedtab'
      },
      controller: ['$scope', '$timeout', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=fitness.map
*/
