// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope) {
    return console.log(scope.model);
  };

  angular.module('manageApp').directive('item', function() {
    return {
      templateUrl: "views/directives/item.html",
      restrict: 'E',
      transclude: true,
      scope: {
        model: '=model'
      },
      controller: ['$scope', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=item.map
*/
