// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(location, scope, element, attrs) {};

  angular.module('manageApp').directive('navcontainer', function() {
    return {
      templateUrl: "views/directives/nav.html",
      restrict: 'E',
      scope: true,
      transclude: true,
      replace: true,
      controller: ['$location', '$scope', '$element', '$attrs', controller]
    };
  });

}).call(this);
