// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function(scope) {
    var Task, query;
    scope.entities = [];
    scope.name = '';
    Task = Parse.Object.extend("Task");
    query = new Parse.Query(Task);
    query.find({
      success: function(results) {
        return scope.$apply(function() {
          return scope.entities = results;
        });
      },
      error: function(error) {
        return console.log(error);
      }
    });
    scope.remove = function(model) {
      return model.destroy({
        success: function() {
          return scope.$apply(function() {
            return scope.entities = _.filter(scope.entities, function(d) {
              return d.id !== model.id;
            });
          });
        },
        error: function(e) {
          return console.log(e);
        }
      });
    };
    scope.add = function(form) {
      var todo;
      todo = new Task();
      todo.set("status", "created");
      todo.set("name", scope.name);
      todo.setACL(new Parse.ACL(Parse.User.current()));
      return todo.save({
        success: function(result) {
          return scope.$apply(function() {
            scope.entities.push(result);
            return scope.name = '';
          });
        },
        error: function(e) {
          return console.log(e);
        }
      });
    };
    scope.onRemove = function(model) {
      return scope.remove(model);
    };
    return scope.onChange = function(model) {
      return model.save({
        success: function() {
          return console.log('updated');
        },
        error: function(e) {
          return console.log(e);
        }
      });
    };
  };

  angular.module('manageApp').directive('todolist', function() {
    return {
      templateUrl: "views/directives/todolist.html",
      restrict: 'E',
      scope: true,
      controller: ['$scope', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=todolist.map
*/
